# Generated by Django 4.2.14 on 2024-07-29 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('poll', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voted_by')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='is_paid_vote',
        ),
    ]
