# Generated by Django 4.2.14 on 2024-08-07 14:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_option_vote_count_poll_vote_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='voted_by',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'user')},
        ),
    ]
